### ISSUE TITLE
ルータでないスイッチに接続したサーバをインポートするとクラッシュする

### ISSUE THREAD

**Issue by tmy** [yamamoto-febc/terraform-provider-sakuracloud#22]
v0.3.5 で、ルータでないスイッチに接続したサーバをインポートすると、以下のエラーで Terraform がクラッシュします。

```
$ terraform import sakuracloud_server.test 112800781551
sakuracloud_server.test: Importing from ID "112800781551"...
sakuracloud_server.test: Import complete!
  Imported sakuracloud_server (ID: 112800781551)
sakuracloud_server.test: Refreshing state... (ID: 112800781551)
Error importing: 1 error(s) occurred:

* sakuracloud_server.test: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: [signal 0xb code=0x1 addr=0x0 pc=0xacb0b]
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: goroutine 21 [running]:
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: panic(0x7a7080, 0xc82000a140)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: github.com/yamamoto-febc/terraform-provider-sakuracloud.resourceSakuraCloudServerRead(0xc8200627e0, 0x7fdb00, 0xc820292240, 0x0, 0x0)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud/resource_sakuracloud_server.go:312 +0x103b
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc82024a660, 0xc820292740, 0x7fdb00, 0xc820292240, 0xc82025a680, 0x0, 0x0)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0x432
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc82024e300, 0xc820292700, 0xc820292740, 0x1, 0x0, 0x0)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:201 +0x1da
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc820153fc0, 0xc820065f10, 0xc8202a0120, 0x0, 0x0)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:482 +0x6a
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: reflect.Value.call(0x73b560, 0x863cb8, 0x13, 0x8aeee8, 0x4, 0xc8202cded8, 0x3, 0x3, 0x0, 0x0, ...)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/usr/local/go/src/reflect/value.go:435 +0x120d
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: reflect.Value.Call(0x73b560, 0x863cb8, 0x13, 0xc8202cded8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/usr/local/go/src/reflect/value.go:303 +0xb1
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: net/rpc.(*service).call(0xc820236300, 0xc8202362c0, 0xc8202600a0, 0xc82026e400, 0xc8200d99c0, 0x60ba60, 0xc820065f10, 0x16, 0x60bac0, 0xc8202a0120, ...)
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: created by net/rpc.(*Server).ServeCodec
2016/07/29 11:36:15 [DEBUG] plugin: terraform-provider-sakuracloud: 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
2016/07/29 11:36:15 [ERROR] root: eval: *terraform.EvalRefresh, err: sakuracloud_server.test: unexpected EOF
2016/07/29 11:36:15 [ERROR] root: eval: *terraform.EvalSequence, err: sakuracloud_server.test: unexpected EOF
2016/07/29 11:36:15 [TRACE] [walkImport] Exiting eval tree: import sakuracloud_server.test result: 112800781551
2016/07/29 11:36:15 [DEBUG] vertex provider.sakuracloud (close), got dep: sakuracloud_server.test (import id: 112800781551)
2016/07/29 11:36:15 [DEBUG] plugin: waiting for all plugin processes to complete...
2016/07/29 11:36:15 [DEBUG] plugin: /Users/tommy/Desktop/sakuracloud/terraform-provider-sakuracloud: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

API の情報を取得してみると、`Subnet` の値が `null` であるため `DefaultRoute` の値が取れないようです。

```json
{
  "Server": {
    "ID": "112800781551",
    (略)
    "Interfaces": [
      {
        "ID": "112800781552",
        "MACAddress": "9C:A3:BA:12:D2:5D",
        "IPAddress": null,
        "UserIPAddress": "192.168.0.123",
        "HostName": null,
        "Switch": {
          "ID": "112800779091",
          "Name": "test",
          "Scope": "user",
          "Subnet": null,
          "UserSubnet": {
            "DefaultRoute": "192.168.0.1",
            "NetworkMaskLen": 24
          }
        },
        "PacketFilter": null
      }
    ],
```

**Comment by yamamoto-febc** [comment]
@tmy 
コントリビューションありがとうございます。
修正PRを作成しました(#23)。
テスト後にマージします。

**Comment by yamamoto-febc** [comment]
@tmy リリースページのバイナリを差し替えました。

https://github.com/yamamoto-febc/terraform-provider-sakuracloud/releases/tag/v0.3.5

上記ページから再度バイナリをダウンロードして試してみてください。

**Comment by tmy** [comment]
ありがとうございます。無事インポートできるようになりました。
